// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3j9imdsBlic94mfRTeTO_4KXzgLKFyOc',
    appId: '1:139618013972:web:5b81af09d2ca6001d6a801',
    messagingSenderId: '139618013972',
    projectId: 'zoto-chat',
    authDomain: 'zoto-chat.firebaseapp.com',
    storageBucket: 'zoto-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHaX0L8FC2e_Dfk8IsIAxifx0Vhk_t3_E',
    appId: '1:139618013972:android:146767c86cce9428d6a801',
    messagingSenderId: '139618013972',
    projectId: 'zoto-chat',
    storageBucket: 'zoto-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNYLpE0IrNaQc5QcBTuQOohDrarKY2ao0',
    appId: '1:139618013972:ios:1bb8dbe01c82a772d6a801',
    messagingSenderId: '139618013972',
    projectId: 'zoto-chat',
    storageBucket: 'zoto-chat.appspot.com',
    androidClientId: '139618013972-mt8a9nvgjm40tmt1esp4bajne621hshc.apps.googleusercontent.com',
    iosClientId: '139618013972-r1v12q85crq9892k6j2tr6h01hgscppd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplicationWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNYLpE0IrNaQc5QcBTuQOohDrarKY2ao0',
    appId: '1:139618013972:ios:1bb8dbe01c82a772d6a801',
    messagingSenderId: '139618013972',
    projectId: 'zoto-chat',
    storageBucket: 'zoto-chat.appspot.com',
    androidClientId: '139618013972-mt8a9nvgjm40tmt1esp4bajne621hshc.apps.googleusercontent.com',
    iosClientId: '139618013972-r1v12q85crq9892k6j2tr6h01hgscppd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApplicationWithFirebase',
  );
}
